### ISSUE TITLE
针对IOS方面，希望增加个性化参数

### ISSUE THREAD

**Issue by lkmvip** [BoyceLig/UnblockNeteaseMusic_GUI#1]
未加参数无法正常使用，加了参数能正常使用

在此贴有详细说明
https://github.com/nondanee/UnblockNeteaseMusic/issues/185

端口方面改成如下增加8081为https转发
-p 8080:8081

再加参数-e如
 -e https://music.163.com

实际如下，能正常被ios使用
node app.js -p 8080:8081 -e http://music.163.com

**Comment by BoyceLig** [comment]
你是说加个局域网转发参数么

**Comment by BoyceLig** [comment]
现在这个GUI是支持Windows，不支持ios

**Comment by lkmvip** [comment]
是启动参数

无所谓了，我已开始使用spotify，放弃网易云了。
